apiVersion: v1
kind: Secret
metadata:
  name: demo-university-registry-secret
  namespace: demo-university
data:
  .dockerconfigjson: DOCKER_CONFIG_JSON_PLACEHOLDER
type: kubernetes.io/dockerconfigjson